// =========================================================
// 📜 KUTIPAN UNTUK KREATOR
// =========================================================
const kutipanList = [
  "Dari satu kamera, tersimpan seribu cerita.",
  "Jangan tunggu viral, buatlah karya yang bernilai.",
  "Kreator hebat lahir dari dusun kecil, tapi mimpi yang besar.",
  "Konten hebat bukan karena alatnya, tapi niatnya.",
  "Konsisten lebih kuat dari sekadar inspirasi.",
  "Setiap upload adalah langkah menuju versi terbaikmu.",
  "Karya kecil yang selesai lebih baik dari ide besar yang disimpan.",
  "Satu video bisa mengubah satu hidup — mungkin hidupmu sendiri.",
  "Kreator bukan yang punya kamera mahal, tapi yang tak berhenti berkarya.",
  "Posting tanpa harapan, tapi dengan tujuan.",
  "Kegagalan pertama bukan akhir — tapi pembuka jalan sukses kedua.",
  "Jangan bandingkan views, bandingkan prosesmu kemarin dan hari ini.",
  "Orang lupa siapa pertama, tapi ingat siapa yang konsisten.",
  "Karya bagus itu bukan sempurna, tapi jujur.",
  "Kreativitas bukan bakat, tapi kebiasaan berpikir beda.",
  "Jika kamu tak punya panggung, buatlah panggungmu sendiri.",
  "Setiap like hanyalah bonus, karya adalah tujuan.",
  "Semakin kamu tulus, semakin orang merasa dekat.",
  "Berkaryalah sampai diam-mu pun punya makna.",
  "Ide itu gratis, eksekusi yang mahal.",
  "Konten bukan hanya visual, tapi juga nilai di dalamnya.",
  "Rekam hari ini, karena besok mungkin sudah berubah.",
  "Kamera hanyalah alat, tapi hatimu adalah lensa sesungguhnya.",
  "Kreator yang baik tahu kapan harus diam dan kapan harus menginspirasi.",
  "Upload tanpa rasa takut — karena setiap karya punya penontonnya sendiri.",
  "Jika dunia tak melihatmu, buat mereka mendengarmu.",
  "Kamu tak perlu sempurna, kamu hanya perlu mulai.",
  "Kreator sejati bukan yang paling cepat, tapi yang paling tahan lama.",
  "Setiap frame punya jiwa, kalau kamu mau menaruh hatimu di sana.",
  "Karya yang jujur tak butuh filter.",
  "Jangan sibuk jadi sempurna, sibuklah jadi nyata.",
  "Kamu tak gagal, kamu hanya sedang diuji.",
  "Kreator besar dimulai dari komentar kecil.",
  "Satu ide gila bisa jadi warisan selamanya.",
  "Jangan cari penonton, bangun komunitas.",
  "Karya hebat tak butuh banyak efek, cukup kejujuran dan konsistensi.",
  "Viral hanyalah efek samping dari niat yang tulus.",
  "Rekam dengan hati, bukan hanya dengan kamera.",
  "Tak ada jalan pintas untuk yang ingin abadi di ingatan orang.",
  "Suara kecilmu mungkin jadi inspirasi besar bagi seseorang.",
  "Jangan takut upload pertama, semua yang besar pernah jadi pemula.",
  "Kreativitas tumbuh di tempat yang penuh kesalahan.",
  "Kamu tak perlu trending, kamu hanya perlu terus hidup lewat karya.",
  "Setiap karya adalah cermin perjalananmu.",
  "Berkaryalah bukan karena disukai, tapi karena kamu suka.",
  "Orang boleh meniru, tapi tak bisa menyalin jiwamu.",
  "Karya yang baik selalu punya waktu untuk dikenang.",
  "Tak ada kata gagal bagi yang terus mencoba.",
  "Kreator sejati tahu bahwa waktu adalah editor terbaiknya.",
  "Bukan views yang membesarkanmu, tapi nilai yang kamu tanam.",
  "Kamu bukan sedang membuat video, kamu sedang meninggalkan jejak sejarah.",
  "Semakin sering gagal, semakin tajam intuisi kreatifmu.",
  "Setiap video adalah bentuk keberanian kecil.",
  "Jangan edit kepribadianmu — cukup videonya.",
  "Cahaya terbaik datang setelah kamu berani menyalakan kamera.",
  "Karya yang benar-benar hidup adalah yang menyentuh hati penontonnya.",
  "Jangan tunggu inspirasi, mulai saja dan biarkan inspirasi menyusul.",
  "Kreativitas bukan tentang punya banyak ide, tapi mengeksekusi satu ide dengan baik.",
  "Karya sederhana bisa jadi luar biasa di mata orang yang tepat.",
  "Dunia tak butuh konten sempurna, dunia butuhmu yang autentik.",
  "Satu posting bisa jadi motivasi bagi ribuan orang tanpa kamu sadari.",
  "Berhenti menilai karyamu sendiri terlalu keras.",
  "Kamu tak bisa menyenangkan semua orang, tapi kamu bisa menginspirasi sebagian.",
  "Tugasmu bukan jadi terkenal, tapi jadi bermanfaat.",
  "Jangan takut terlihat bodoh — semua kreator hebat pernah melalui itu.",
  "Setiap video adalah bukti kamu berani berbicara.",
  "Karya yang bagus adalah yang membuat orang merasa sesuatu.",
  "Kalau ide tak datang, ambil kamera dan mulai saja.",
  "Semakin kamu belajar, semakin banyak ide yang bisa lahir.",
  "Kreativitasmu bukan untuk dibandingkan, tapi untuk dibagikan.",
  "Jika kamu ingin diingat, buatlah karya yang tulus.",
  "Semua orang bisa meniru gayamu, tapi tidak bisa meniru jiwamu.",
  "Tak ada karya kecil jika dibuat dengan niat besar.",
  "Jangan takut mulai jelek, karena dari situ kamu tumbuh.",
  "Kreator yang berhenti karena takut kritik, kehilangan kesempatan tumbuh.",
  "Teruslah merekam, karena waktu tak bisa diulang.",
  "Satu karya hari ini lebih berarti daripada seribu ide besok.",
  "Kreativitas sejati datang dari rasa ingin tahu yang tak pernah padam.",
  "Semakin kamu jujur, semakin dunia mendengarkan.",
  "Tak semua konten harus viral, tapi semua harus bermakna.",
  "Karya terbaik lahir dari hati yang berani gagal.",
  "Jangan buat untuk semua orang, buat untuk satu orang yang butuh.",
  "Kreator sejati tak butuh pengakuan — karyanya sudah cukup bicara.",
  "Setiap like hanyalah bonus, proses adalah hadiah sebenarnya.",
  "Semakin kamu tulus, semakin besar dampakmu.",
  "Berkaryalah seolah tak ada algoritma.",
  "Kreator hebat bukan yang viral, tapi yang bertahan lama.",
  "Kamu tak sedang bersaing, kamu sedang berkembang.",
  "Dunia digital luas, tapi tempatmu selalu ada di dalamnya.",
  "Konten adalah jembatan antara mimpi dan kenyataan.",
  "Satu karya hari ini bisa jadi alasan orang lain tak menyerah besok.",
  "Jangan kejar kesempurnaan, kejar keberlanjutan.",
  "Karya hebat selalu dimulai dari keberanian kecil.",
  "Berkarya bukan karena harus, tapi karena ingin berbagi.",
  "Kreator bukan sekadar pembuat konten — dia pembentuk masa depan.",
  "Jangan takut berbeda, karena yang berbeda sering kali menjadi pembuka jalan baru. — Najwa Shihab",
  "Kreativitas bukan tentang alat, tapi tentang cara berpikir. — Pandji Pragiwaksono",
  "Konten yang baik lahir dari hati, bukan hanya dari kamera. — Raditya Dika",
  "Kalau kamu tak mulai sekarang, kapan lagi orang akan mengenal karyamu? — Jerome Polin",
  "Jangan tunggu sempurna, karena kesempurnaan datang setelah mencoba. — Deddy Corbuzier",
  "Berkarya itu bukan soal viral, tapi soal dampak. — Gita Wirjawan",
  "Ide besar sering muncul dari hal kecil yang diperhatikan dengan sungguh-sungguh. — Najwa Shihab",
  "Semakin kamu tulus berkarya, semakin kuat resonansinya. — Ernest Prakasa",
  "Kreator sejati tak meniru, tapi terinspirasi. — Raditya Dika",
  "Kalau kamu tidak membuat karya, kamu hanya akan jadi penonton. — Denny Caknan",
];