const kutipanList = [
  // ===== KUTIPAN ORIGINAL UNTUK KREATOR =====
  "Konten hebat bukan karena alatnya, tapi niatnya.",
  "Konsisten lebih kuat dari sekadar inspirasi.",
  "Setiap upload adalah langkah menuju versi terbaikmu.",
  "Karya kecil yang selesai lebih baik dari ide besar yang disimpan.",
  "Satu video bisa mengubah satu hidup — mungkin hidupmu sendiri.",
  "Kreator bukan yang punya kamera mahal, tapi yang tak berhenti berkarya.",
  "Posting tanpa harapan, tapi dengan tujuan.",
  "Kegagalan pertama bukan akhir — tapi pembuka jalan sukses kedua.",
  "Jangan bandingkan views, bandingkan prosesmu kemarin dan hari ini.",
  "Orang lupa siapa pertama, tapi ingat siapa yang konsisten.",
  "Karya bagus itu bukan sempurna, tapi jujur.",
  "Kreativitas bukan bakat, tapi kebiasaan berpikir beda.",
  "Jika kamu tak punya panggung, buatlah panggungmu sendiri.",
  "Setiap like hanyalah bonus, karya adalah tujuan.",
  "Semakin kamu tulus, semakin orang merasa dekat.",
  "Berkaryalah sampai diam-mu pun punya makna.",
  "Ide itu gratis, eksekusi yang mahal.",
  "Konten bukan hanya visual, tapi juga nilai di dalamnya.",
  "Rekam hari ini, karena besok mungkin sudah berubah.",
  "Kamera hanyalah alat, tapi hatimu adalah lensa sesungguhnya.",
  "Kreator yang baik tahu kapan harus diam dan kapan harus menginspirasi.",
  "Upload tanpa rasa takut — karena setiap karya punya penontonnya sendiri.",
  "Jika dunia tak melihatmu, buat mereka mendengarmu.",
  "Kamu tak perlu sempurna, kamu hanya perlu mulai.",
  "Kreator sejati bukan yang paling cepat, tapi yang paling tahan lama.",
  "Setiap frame punya jiwa, kalau kamu mau menaruh hatimu di sana.",
  "Karya yang jujur tak butuh filter.",
  "Jangan sibuk jadi sempurna, sibuklah jadi nyata.",
  "Kamu tak gagal, kamu hanya sedang diuji.",
  "Kreator besar dimulai dari komentar kecil.",
  "Satu ide gila bisa jadi warisan selamanya.",
  "Jangan cari penonton, bangun komunitas.",
  "Karya hebat tak butuh banyak efek, cukup kejujuran dan konsistensi.",
  "Viral hanyalah efek samping dari niat yang tulus.",
  "Rekam dengan hati, bukan hanya dengan kamera.",
  "Tak ada jalan pintas untuk yang ingin abadi di ingatan orang.",
  "Suara kecilmu mungkin jadi inspirasi besar bagi seseorang.",
  "Jangan takut upload pertama, semua yang besar pernah jadi pemula.",
  "Kreativitas tumbuh di tempat yang penuh kesalahan.",
  "Kamu tak perlu trending, kamu hanya perlu terus hidup lewat karya.",
  "Setiap karya adalah cermin perjalananmu.",
  "Berkaryalah bukan karena disukai, tapi karena kamu suka.",
  "Orang boleh meniru, tapi tak bisa menyalin jiwamu.",
  "Karya yang baik selalu punya waktu untuk dikenang.",
  "Tak ada kata gagal bagi yang terus mencoba.",
  "Kreator sejati tahu bahwa waktu adalah editor terbaiknya.",
  "Bukan views yang membesarkanmu, tapi nilai yang kamu tanam.",
  "Kamu bukan sedang membuat video, kamu sedang meninggalkan jejak sejarah.",
  "Semakin sering gagal, semakin tajam intuisi kreatifmu.",
  "Setiap video adalah bentuk keberanian kecil.",
  "Jangan edit kepribadianmu — cukup videonya.",
  "Cahaya terbaik datang setelah kamu berani menyalakan kamera.",
  "Karya yang benar-benar hidup adalah yang menyentuh hati penontonnya.",
  "Jangan tunggu inspirasi, mulai saja dan biarkan inspirasi menyusul.",
  "Kreativitas bukan tentang punya banyak ide, tapi mengeksekusi satu ide dengan baik.",
  "Karya sederhana bisa jadi luar biasa di mata orang yang tepat.",
  "Dunia tak butuh konten sempurna, dunia butuhmu yang autentik.",
  "Satu posting bisa jadi motivasi bagi ribuan orang tanpa kamu sadari.",
  "Berhenti menilai karyamu sendiri terlalu keras.",
  "Kamu tak bisa menyenangkan semua orang, tapi kamu bisa menginspirasi sebagian.",
  "Tugasmu bukan jadi terkenal, tapi jadi bermanfaat.",
  "Jangan takut terlihat bodoh — semua kreator hebat pernah melalui itu.",
  "Setiap video adalah bukti kamu berani berbicara.",
  "Karya yang bagus adalah yang membuat orang merasa sesuatu.",
  "Kalau ide tak datang, ambil kamera dan mulai saja.",
  "Semakin kamu belajar, semakin banyak ide yang bisa lahir.",
  "Kreativitasmu bukan untuk dibandingkan, tapi untuk dibagikan.",
  "Jika kamu ingin diingat, buatlah karya yang tulus.",
  "Semua orang bisa meniru gayamu, tapi tidak bisa meniru jiwamu.",
  "Tak ada karya kecil jika dibuat dengan niat besar.",
  "Jangan takut mulai jelek, karena dari situ kamu tumbuh.",
  "Kreator yang berhenti karena takut kritik, kehilangan kesempatan tumbuh.",
  "Teruslah merekam, karena waktu tak bisa diulang.",
  "Satu karya hari ini lebih berarti daripada seribu ide besok.",
  "Kreativitas sejati datang dari rasa ingin tahu yang tak pernah padam.",
  "Semakin kamu jujur, semakin dunia mendengarkan.",
  "Tak semua konten harus viral, tapi semua harus bermakna.",
  "Karya terbaik lahir dari hati yang berani gagal.",
  "Jangan buat untuk semua orang, buat untuk satu orang yang butuh.",
  "Kreator sejati tak butuh pengakuan — karyanya sudah cukup bicara.",
  "Setiap like hanyalah bonus, proses adalah hadiah sebenarnya.",
  "Semakin kamu tulus, semakin besar dampakmu.",
  "Berkaryalah seolah tak ada algoritma.",
  "Kreator hebat bukan yang viral, tapi yang bertahan lama.",
  "Kamu tak sedang bersaing, kamu sedang berkembang.",
  "Dunia digital luas, tapi tempatmu selalu ada di dalamnya.",
  "Konten adalah jembatan antara mimpi dan kenyataan.",
  "Satu karya hari ini bisa jadi alasan orang lain tak menyerah besok.",
  "Jangan kejar kesempurnaan, kejar keberlanjutan.",
  "Karya hebat selalu dimulai dari keberanian kecil.",
  "Berkarya bukan karena harus, tapi karena ingin berbagi.",
  "Kreator bukan sekadar pembuat konten — dia pembentuk masa depan.",

  // ===== KUTIPAN DARI TOKOH DUNIA =====
  "“Creativity is intelligence having fun.” – Albert Einstein",
  "“The best way to predict the future is to create it.” – Peter Drucker",
  "“You don’t have to be great to start, but you have to start to be great.” – Zig Ziglar",
  "“Don’t wait for opportunity. Create it.” – George Bernard Shaw",
  "“Your first 10,000 photographs are your worst.” – Henri Cartier-Bresson",
  "“Make something people want.” – Paul Graham",
  "“Done is better than perfect.” – Sheryl Sandberg",
  "“Be so good they can’t ignore you.” – Steve Martin",
  "“If you can’t stop thinking about it, don’t stop working for it.” – Michael Jordan",
  "“It’s not about ideas. It’s about making ideas happen.” – Scott Belsky",
  "“Your story matters. Share it.” – Gary Vaynerchuk",
  "“You don’t find your style. Your style finds you after you make a lot of stuff.” – Casey Neistat",
  "“The more I practice, the luckier I get.” – Gary Player",
  "“The secret of getting ahead is getting started.” – Mark Twain",
  "“Perfection is the enemy of progress.” – Winston Churchill",
  "“Create what you wish existed.” – Anonymous",
  "“Don’t compare your beginning to someone else’s middle.” – Jon Acuff",
  "“Start where you are. Use what you have. Do what you can.” – Arthur Ashe",
  "“Inspiration exists, but it has to find you working.” – Pablo Picasso",
  "“Every artist was first an amateur.” – Ralph Waldo Emerson",

// ===== TAMBAHAN 100 KUTIPAN =====
  "Kamera tak pernah bohong, tapi bisa menangkap kebohongan dengan indah.",
  "Kalau ide tak datang, pergi menyapu dulu — kadang inspirasi muncul saat bekerja.",
  "Tak semua video harus viral, yang penting berkesan.",
  "Kreativitas itu seperti otot — semakin sering dipakai, semakin kuat.",
  "Kadang ide terbaik datang saat kamu tak sengaja menumpahkan kopi.",
  "Kalau semua orang bilang idemu aneh, berarti kamu di jalur yang benar.",
  "Jangan takut terlihat aneh, justru di situlah keunikanmu.",
  "Semakin kamu gagal, semakin kamu tahu cara membuat yang berhasil.",
  "Karya tanpa niat hanya jadi file di galeri.",
  "Kamu tak butuh ribuan penonton, cukup satu yang benar-benar paham pesannya.",
  "Karya yang baik tak harus ramai, cukup punya makna.",
  "Kalau kamu tidak bangga dengan karyamu, siapa lagi?",
  "Kreator sejati tidak sibuk menjelaskan — karyanya sudah bicara.",
  "Tak perlu lighting mahal, cukup cahaya pagi dan niat besar.",
  "Kamera boleh sederhana, tapi idemu harus luar biasa.",
  "Berkarya itu seperti menanam: hasilnya tak langsung, tapi pasti tumbuh.",
  "Setiap konten adalah jejak pikiranmu yang terekam.",
  "Kreator yang baik tahu kapan berhenti meniru dan mulai menjadi diri sendiri.",
  "Bukan algoritma yang menahanmu, tapi rasa takutmu sendiri.",
  "Kamu tak butuh izin untuk menjadi kreatif.",
  "Berkarya bukan untuk membuktikan, tapi untuk berkontribusi.",
  "Kamu tak sedang berlomba, kamu sedang bercerita.",
  "Jangan biarkan komentar buruk mematikan ide bagus.",
  "Setiap kreator punya masa canggung — tapi itu tanda kamu sedang tumbuh.",
  "Sebuah ide kecil bisa jadi sesuatu yang besar kalau kamu tekuni.",
  "Kamu tak perlu sempurna untuk menginspirasi.",
  "Karya hebat dimulai dari rasa penasaran.",
  "Tak perlu menunggu mood, disiplin adalah mood terbaik kreator.",
  "Kreativitas bukan meniru, tapi menemukan cara baru.",
  "Kontenmu mungkin biasa bagimu, tapi luar biasa bagi orang lain.",
  "Buat karya yang kamu banggakan, bukan yang semua orang sukai.",
  "Kamu bisa berhenti kapan saja — tapi jangan hari ini.",
  "Karya terbaik lahir dari waktu yang kamu curi untuk bermimpi.",
  "Kreator hebat tidak sibuk mencari perhatian, tapi memberi manfaat.",
  "Bukan views yang menentukan nilaimu, tapi dampakmu.",
  "Setiap upload adalah bukti kamu berani jadi dirimu sendiri.",
  "Kalau kamu menunggu siap, kamu tak akan pernah mulai.",
  "Tak perlu alat mahal untuk membuat orang tersentuh.",
  "Kreator sejati tahu: ide datang dari kehidupan nyata.",
  "Kamu bukan gagal, kamu sedang belajar cara lain.",
  "Karya itu seperti nasi — kalau terlalu lama didiamkan, basi.",
  "Inspirasi bisa datang dari sawah, bukan hanya dari kota.",
  "Berkaryalah seperti petani menanam: dengan sabar dan keyakinan.",
  "Kalau kamu tak menemukan jalan, buat jalannya sendiri.",
  "Kreativitas bukan soal bakat, tapi keberanian untuk mencoba.",
  "Tak perlu panggung besar, cukup ruang kecil dan semangat besar.",
  "Kamu tak butuh semua orang suka, cukup satu orang tersentuh.",
  "Kreator sejati menulis sejarah dengan setiap unggahan.",
  "Karya terbaik lahir dari hati yang sedang berjuang.",
  "Kalau kamu tak punya motivasi, ingat alasanmu mulai dulu.",
  "Kreator bukan hanya membuat konten, tapi juga kenangan.",
  "Jangan tunggu kesempatan, buat kesempatan itu sendiri.",
  "Kamu tak perlu viral untuk berpengaruh.",
  "Kreator sejati tak sibuk jadi terkenal, tapi jadi berguna.",
  "Karya adalah cermin dari keberanianmu melawan rasa malas.",
  "Orang yang mengeluh tak punya waktu, biasanya buang waktu untuk mengeluh.",
  "Kalau kamu ragu dengan hasilmu, upload saja — biar dunia menilai.",
  "Karya kecil hari ini lebih baik dari rencana besar besok.",
  "Setiap video punya penonton yang ditakdirkan untuk menontonnya.",
  "Kreativitas tumbuh dari kesabaran, bukan dari terburu-buru.",
  "Kalau kamu jatuh, bawa kamera — siapa tahu jadi konten.",
  "Karya tak perlu panjang, asal mengena.",
  "Kalau idemu ditertawakan, anggap saja kamu sedang selangkah lebih maju.",
  "Jangan takut ide dicuri — tak ada yang bisa meniru semangatmu.",
  "Berkaryalah sampai orang berhenti menanyakan alasanmu.",
  "Kamu tak perlu sempurna untuk berani tampil.",
  "Kadang diam dan mengamati lebih inspiratif daripada bicara.",
  "Jangan ukur kreativitas dari jumlah likes.",
  "Kreativitas adalah cara lain untuk berterima kasih pada hidup.",
  "Satu konten jujur bisa mengalahkan seribu yang palsu.",
  "Kalau kamu terus membandingkan, kamu tak akan pernah menciptakan.",
  "Semakin kamu menunda, semakin jauh kamu dari mimpi.",
  "Kamu tak butuh validasi, cukup keyakinan.",
  "Kreator besar bukan yang punya ide besar, tapi yang berani mulai kecil.",
  "Kalau dunia tak menontonmu, teruslah berkarya sampai mereka menyesal.",
  "Setiap frame punya cerita, setiap detik punya pesan.",
  "Kamu tak harus luar biasa untuk menginspirasi, cukup tulus.",
  "Karya yang tulus selalu menemukan jalannya.",
  "Kalau kamu malas hari ini, bayangkan dirimu menyesal besok.",
  "Kreativitas tak butuh alasan, cukup keberanian.",
  "Kalau kamu terus mencoba, gagal pun jadi pelajaran mahal.",
  "Berkarya bukan karena ingin dilihat, tapi karena tak bisa diam.",
  "Kamu tak bisa mengontrol hasil, tapi bisa mengontrol usaha.",
  "Kreativitas bukan tentang tren, tapi tentang keaslian.",
  "Satu video bisa jadi warisan yang abadi.",
  "Kalau kamu tak yakin, buat dulu, pikir nanti.",
  "Berkarya itu seperti bercocok tanam — hasilnya datang bagi yang sabar.",
  "Kreator yang berhenti karena lelah, tak akan tahu betapa dekat dia dengan sukses.",
  "Kalau kamu takut jelek, kamu tak akan pernah jadi baik.",
  "Setiap upload adalah latihan percaya diri.",
  "Kreativitas datang saat kamu berhenti takut gagal.",
  "Tak perlu ribut soal siapa paling hebat, cukup siapa paling niat.",
  "Karya yang hidup tak perlu dipaksa terlihat sempurna.",
  "Berkarya adalah bentuk doa tanpa kata.",
  "Kalau kamu tak punya penonton, jadilah penonton bagi karya orang lain.",
  "Setiap ide adalah benih, jangan biarkan mati sebelum tumbuh.",
  "Kreator sejati tetap berkarya bahkan tanpa kamera.",
  "Tak perlu semua orang paham — cukup satu orang tersentuh.",
  "Karya yang dibuat dengan hati akan menemukan hati lain untuk tinggal.",
  "Berkaryalah seperti petani menanam harapan, bukan sekadar panen pujian.",
  "Kalau kamu ingin dihargai, hargai dulu prosesmu sendiri.",
  "Kreativitas tak punya batas — kecuali kamu sendiri yang membatasinya.",
  "Dunia mungkin lupa wajahmu, tapi akan ingat karyamu.",
  "Setiap hari adalah kesempatan baru untuk mencipta sesuatu yang berarti.",
  "Berkaryalah dengan niat baik, karena niat itu menular.",
  "Kalau kamu tak mulai hari ini, kapan lagi kamu akan bangga?",
// Kutipan Orang Indo
"Jangan takut berbeda, karena yang berbeda sering kali menjadi pembuka jalan baru. — Najwa Shihab",
  "Kreativitas bukan tentang alat, tapi tentang cara berpikir. — Pandji Pragiwaksono",
  "Konten yang baik lahir dari hati, bukan hanya dari kamera. — Raditya Dika",
  "Kalau kamu tak mulai sekarang, kapan lagi orang akan mengenal karyamu? — Jerome Polin",
  "Jangan tunggu sempurna, karena kesempurnaan datang setelah mencoba. — Deddy Corbuzier",
  "Berkarya itu bukan soal viral, tapi soal dampak. — Gita Wirjawan",
  "Ide besar sering muncul dari hal kecil yang diperhatikan dengan sungguh-sungguh. — Najwa Shihab",
  "Semakin kamu tulus berkarya, semakin kuat resonansinya. — Ernest Prakasa",
  "Kreator sejati tak meniru, tapi terinspirasi. — Raditya Dika",
  "Kalau kamu tidak membuat karya, kamu hanya akan jadi penonton. — Denny Caknan",
  "Dunia digital memberi panggung bagi siapa pun yang berani tampil. — Jerome Polin",
  "Tak perlu terkenal, cukup karya kita berguna. — Najwa Shihab",
  "Konten bukan sekadar hiburan, tapi juga cara membangun perubahan. — Gita Wirjawan",
  "Yang kamu bagikan hari ini bisa jadi inspirasi bagi orang lain besok. — Deddy Corbuzier",
  "Buatlah karya yang kamu sendiri bangga menontonnya. — Ernest Prakasa",
  "Setiap video punya jiwa, tergantung siapa yang memegang kameranya. — Raditya Dika",
  "Teknologi hanyalah alat, manusia tetap sumber ide. — Pandji Pragiwaksono",
  "Kreativitas itu latihan, bukan keajaiban. — Jerome Polin",
  "Kalau niatmu tulus, algoritma akan menemukanmu. — Najwa Shihab",
  "Jadilah versi terbaik dirimu di depan kamera, bukan versi orang lain. — Deddy Corbuzier",
  "Berkarya bukan soal siapa paling cepat, tapi siapa paling konsisten. — Ernest Prakasa",
  "Orang boleh meniru gayamu, tapi tak bisa meniru keikhlasanmu. — Gita Wirjawan",
  "Yang membuat konten menarik bukan efeknya, tapi maknanya. — Raditya Dika",
  "Jangan takut gagal upload, takutlah kalau kamu berhenti berkarya. — Jerome Polin",
  "Konten bagus itu seperti nasi goreng, sederhana tapi bikin nagih. — Pandji Pragiwaksono",
  "Suara kecilmu di dunia maya bisa mengguncang dunia nyata. — Najwa Shihab",
  "Karya adalah bukti kamu pernah berjuang. — Ernest Prakasa",
  "Kreativitas adalah keberanian untuk tampil tanpa takut salah. — Deddy Corbuzier",
  "Kontenmu mencerminkan caramu memandang dunia. — Raditya Dika",
  "Bukan seberapa sering kamu upload, tapi seberapa bermakna pesanmu. — Gita Wirjawan",
  "Semakin kamu memahami dirimu, semakin kuat identitas karyamu. — Najwa Shihab",
  "Berkarya bukan untuk disukai semua orang, tapi untuk menyentuh yang tepat. — Ernest Prakasa",
  "Kalau kamu punya ide, jangan tunda — dunia menunggu versimu. — Jerome Polin",
  "Tak perlu alat mahal, cukup niat yang menyala. — Deddy Corbuzier",
  "Semua orang bisa jadi kreator, asal berani mulai. — Raditya Dika",
  "Kreativitas itu seperti otot, makin sering dipakai makin kuat. — Pandji Pragiwaksono",
  "Setiap karya adalah cermin pikiran dan perasaan pembuatnya. — Najwa Shihab",
  "Jangan berhenti karena tidak dilihat, teruslah karena kamu percaya. — Ernest Prakasa",
  "Kreator hebat bukan yang punya banyak penonton, tapi banyak makna. — Gita Wirjawan",
  "Karya terbaik lahir dari kejujuran, bukan dari pencitraan. — Raditya Dika",
  "Tak perlu menunggu inspirasi datang, panggil dia lewat kerja keras. — Jerome Polin",
  "Buat konten dengan hati, bukan demi angka. — Najwa Shihab",
  "Jangan takut kecil, semua besar berawal dari nol. — Deddy Corbuzier",
  "Yang penting bukan siapa yang pertama, tapi siapa yang bertahan. — Ernest Prakasa",
  "Kreator sejati itu terus belajar, bukan hanya terus tampil. — Pandji Pragiwaksono",
  "Kalau kamu ingin diingat, buatlah sesuatu yang layak diingat. — Gita Wirjawan",
  "Kamera bisa merekam gambar, tapi hati merekam makna. — Raditya Dika",
  "Jangan tunggu sempurna untuk mulai, mulai dulu untuk jadi sempurna. — Najwa Shihab",
  "Karya tak pernah bohong, ia menunjukkan siapa dirimu sebenarnya. — Ernest Prakasa"
];

